# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2.6

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build Server And Web App Package To Serve from Express Server
          command: yarn build

  eslint:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Eslint  On ExpressJS Code Base
          command: yarn eslint
      - run:
          name: Run Eslint On React Code Base
          command: yarn eslint:react
  
  prettier:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Prettier On ExpressJS Code Base
          command: yarn prettier:fix
      - run:
          name: Run Prettier On React Code Base
          command: yarn prettier:fix:react

  ts-lints:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Prettier On ExpressJS Code Base
          command: yarn run tsc --noEmit
      - run:
          name: Run Prettier On React Code Base
          command: cd client &&  yarn run tsc --noEmit

  tests:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: NodeJS Tests On Express JS Server
          command: yarn test
      - run:
          name: Run Tests On React Code Base
          command: cd client && yarn test

workflows:
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  express-js-app:
    jobs:
      - ts-lints:
            name: TS Lints
      - prettier:
            name: Prettier
      - eslint:
            name: ESLint
      - tests:
            name: Code Tests
      - build:
            name: Build
      - heroku/deploy-via-git:
            name: Deploy
            pre-steps:
                -  run: yarn install && yarn build
